[functions.igdb-proxy]
verify_jwt = false

[functions.steam-account]
verify_jwt = false

[functions.trusted-admin]
verify_jwt = false

[functions.trusted-profile]
verify_jwt = false

[functions.trusted-coin]
verify_jwt = false

[functions.trusted-post]
verify_jwt = false

[functions.trusted-comment]
verify_jwt = false

[functions.trusted-comment-reaction]
verify_jwt = false

[functions.mux-video]
verify_jwt = false

[functions.mux-webhook]
verify_jwt = false

[functions.trusted-follow]
verify_jwt = false
