create table if not exists public.custom_communities (
  id integer generated by default as identity primary key,
  community_game_id integer generated always as ((-300000 - id)) stored unique,
  slug text not null unique,
  title text not null,
  subtitle text not null,
  body text not null,
  creator_user_id uuid not null references public.profiles (id) on delete cascade,
  moderation_state text not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint custom_communities_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint custom_communities_title_length check (char_length(btrim(title)) between 3 and 60),
  constraint custom_communities_subtitle_length check (char_length(btrim(subtitle)) between 10 and 140),
  constraint custom_communities_body_length check (char_length(btrim(body)) between 10 and 600),
  constraint custom_communities_moderation_state_valid check (moderation_state in ('active', 'hidden'))
);

create table if not exists public.custom_community_bans (
  id uuid primary key default gen_random_uuid(),
  community_id integer not null references public.custom_communities (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  banned_by uuid references public.profiles (id) on delete set null,
  reason text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint custom_community_bans_unique_user unique (community_id, user_id),
  constraint custom_community_bans_reason_length check (reason is null or char_length(reason) <= 240)
);

create index if not exists custom_communities_creator_user_id_idx on public.custom_communities (creator_user_id);
create index if not exists custom_communities_state_created_idx on public.custom_communities (moderation_state, created_at desc);
create index if not exists custom_community_bans_user_id_idx on public.custom_community_bans (user_id);

alter table public.custom_communities enable row level security;
alter table public.custom_community_bans enable row level security;

drop policy if exists "Authenticated users can view active custom communities" on public.custom_communities;
create policy "Authenticated users can view active custom communities"
on public.custom_communities
for select
to authenticated
using (moderation_state = 'active' or creator_user_id = auth.uid() or public.is_platform_staff(auth.uid()));

drop policy if exists "Service role manages custom communities" on public.custom_communities;
create policy "Service role manages custom communities"
on public.custom_communities
for all
to service_role
using (true)
with check (true);

drop policy if exists "Users can view relevant custom community bans" on public.custom_community_bans;
create policy "Users can view relevant custom community bans"
on public.custom_community_bans
for select
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public.custom_communities c
    where c.id = community_id
      and (c.creator_user_id = auth.uid() or public.is_platform_staff(auth.uid()))
  )
);

drop policy if exists "Service role manages custom community bans" on public.custom_community_bans;
create policy "Service role manages custom community bans"
on public.custom_community_bans
for all
to service_role
using (true)
with check (true);
